version: '3.0' # docker-compose version
services: 
    express:
        build: 
            context: .
            dockerfile: Dockerfile
           ports: 
            -"5000:5000"
            depends_on: 
                - db
            environment:
                    -MONGO_URI = 